#!/bin/sh

echo "Building for Windows ..."
GOOS=windows go build -o windows/serve.exe serve.go

echo "Building for Mac (darwin) ..."
GOOS=darwin go build -o mac/serve serve.go

echo "Building for Linux ..."
env GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o linux/serve serve.go
